New-Item -ItemType Directory -Force -Path docs | Out-Null
$LOGFILE = "docs/demo_execution_logs.txt"

"🚀 Starting Quantum-Safe CRE Flagship Pipeline (DEBUG MODE)...`n" | Out-File -FilePath $LOGFILE
"==========================================================" | Out-File -FilePath $LOGFILE -Append
"[PHASE 1] Local Client: Post-Quantum Intent Generation" | Out-File -FilePath $LOGFILE -Append
"==========================================================" | Out-File -FilePath $LOGFILE -Append
Set-Location 1-client 
$env:RUST_LOG = "client=debug,crypto=debug,storage=debug"
cargo run 2>&1 | Tee-Object -FilePath "..\$LOGFILE" -Append
if ($LASTEXITCODE -ne 0) {
    Write-Host "❌ [FATAL ERROR] Phase 1 Rust Client failed." -ForegroundColor Red
    exit $LASTEXITCODE
}
Set-Location ..

"`n==========================================================" | Out-File -FilePath $LOGFILE -Append
"[PHASE 2] Docker execution bounding" | Out-File -FilePath $LOGFILE -Append
"==========================================================" | Out-File -FilePath $LOGFILE -Append
$IMAGE = docker images -q zkvm-coprocessor
if ([string]::IsNullOrWhiteSpace($IMAGE)) {
    "Building Encapsulated Container since it does not exist..." | Out-File -FilePath $LOGFILE -Append
    docker build -t zkvm-coprocessor . 2>&1 | Tee-Object -FilePath $LOGFILE -Append
    if ($LASTEXITCODE -ne 0) {
        Write-Host "❌ [FATAL ERROR] Phase 2 Docker Build failed." -ForegroundColor Red
        exit $LASTEXITCODE
    }
} else {
    "zkvm-coprocessor image already found. Bypassing redundant build logic." | Out-File -FilePath $LOGFILE -Append
}

"Booting SP1 Coprocessor to compute STARK matrix natively..." | Out-File -FilePath $LOGFILE -Append
docker run --rm -v "${PWD}:/app/output" -v "${PWD}/1-client/intent.json:/app/1-client/intent.json" zkvm-coprocessor 2>&1 | Tee-Object -FilePath $LOGFILE -Append

"`n==========================================================" | Out-File -FilePath $LOGFILE -Append
"[PHASE 3 & 4] Chainlink DON Orchestration and Live Settlement" | Out-File -FilePath $LOGFILE -Append
"==========================================================" | Out-File -FilePath $LOGFILE -Append

if (-Not (Test-Path "proof.json")) {
    Write-Host "❌ [FATAL ERROR] STARK proof.json was not generated by SP1." -ForegroundColor Red
    exit 1
}

$proofData = Get-Content "proof.json" -Raw | ConvertFrom-Json
Set-Location 3-chainlink-cre 

"export const STARK_PROOF = { message: 'Transfer 10 USDC', proofBytes: '$($proofData.proofBytes)', publicValues: '$($proofData.publicValues)' };" | Out-File -FilePath intent_payload.ts -Encoding utf8

"Booting official Chainlink CRE environment in Linux Sandbox..." | Out-File -FilePath "..\$LOGFILE" -Append
docker build -t cre-node-env . 2>&1 | Tee-Object -FilePath "..\$LOGFILE" -Append
docker run --rm --env-file ../.env -v "${HOME}/.cre:/root/.cre" -v "${PWD}/node_modules:/app/node_modules" cre-node-env 2>&1 | Tee-Object -FilePath "..\$LOGFILE" -Append
$npxStatus = $LASTEXITCODE
Set-Location ..

if ($npxStatus -ne 0) {
    "`n❌ [FATAL ERROR] Chainlink DON Orchestration crashed. Check logs." | Out-File -FilePath $LOGFILE -Append
    Write-Host "❌ [FATAL ERROR] Phase 3/4 Orchestration failed." -ForegroundColor Red
    exit $npxStatus
}

"`n✅ Flagship validation succeeded! Full trace captured in $LOGFILE" | Out-File -FilePath $LOGFILE -Append
Write-Host "✅ Flagship validation succeeded!" -ForegroundColor Green
