#!/bin/bash
set -e
set -o pipefail # CRITICAL: Prevents 'tee' from masking crashed exit codes

mkdir -p docs
LOGFILE="docs/demo_execution_logs.txt"

echo "🚀 Starting Quantum-Safe CRE Flagship Pipeline (DEBUG MODE)..." | tee $LOGFILE
echo "" | tee -a $LOGFILE
echo "==========================================================" | tee -a $LOGFILE
echo "[PHASE 1] Local Client: Post-Quantum Intent Generation" | tee -a $LOGFILE
echo "==========================================================" | tee -a $LOGFILE
cd 1-client 
RUST_LOG=client=debug,crypto=debug,storage=debug cargo run 2>&1 | tee -a ../$LOGFILE
cd ..

echo "" | tee -a $LOGFILE
echo "==========================================================" | tee -a $LOGFILE
echo "[PHASE 2] Docker execution bounding" | tee -a $LOGFILE
echo "==========================================================" | tee -a $LOGFILE
if [[ "$(docker images -q zkvm-coprocessor 2> /dev/null)" == "" ]]; then
  echo "Building Encapsulated Container since it does not exist..." | tee -a $LOGFILE
  docker build -t zkvm-coprocessor . 2>&1 | tee -a ../$LOGFILE
else
  echo "zkvm-coprocessor image already found. Bypassing redundant build logic." | tee -a $LOGFILE
fi

echo "Booting SP1 Coprocessor to compute STARK matrix natively..." | tee -a $LOGFILE
docker run --rm -v "${PWD}:/app/output" -v "${PWD}/1-client/intent.json:/app/1-client/intent.json" zkvm-coprocessor 2>&1 | tee -a ../$LOGFILE

echo "" | tee -a $LOGFILE
echo "==========================================================" | tee -a $LOGFILE
echo "[PHASE 3 & 4] Chainlink DON Orchestration and Live Settlement" | tee -a $LOGFILE
echo "==========================================================" | tee -a $LOGFILE

if [ ! -f proof.json ]; then
    echo "❌ [FATAL ERROR] STARK proof.json was not generated by SP1." | tee -a $LOGFILE
    exit 1
fi

export PROOF_BYTES=$(grep -o '"proofBytes"[^"]*"[^"]*"' proof.json | cut -d'"' -f4)
export PUBLIC_VALUES=$(grep -o '"publicValues"[^"]*"[^"]*"' proof.json | cut -d'"' -f4)

cd 3-chainlink-cre 

# Bridge the output from Phase 2 into Phase 3's WASM compilation context natively
echo "export const STARK_PROOF = { message: 'Transfer 10 USDC', proofBytes: '${PROOF_BYTES}', publicValues: '${PUBLIC_VALUES}' };" > intent_payload.ts

echo "Booting official Chainlink CRE environment in Linux Sandbox..." | tee -a ../$LOGFILE
# Build and run the real CRE simulation
if [[ "$(docker images -q cre-node-env 2> /dev/null)" == "" ]]; then
  docker build -t cre-node-env . 2>&1 | tee -a ../$LOGFILE
else
  echo "cre-node-env image already found. Bypassing redundant build logic." | tee -a ../$LOGFILE
fi
docker run --rm --env-file ../.env -v "${HOME}/.cre:/root/.cre" -v "${PWD}/node_modules:/app/node_modules" cre-node-env 2>&1 | tee -a ../$LOGFILE

cd ..

echo "" | tee -a $LOGFILE
echo "✅ Flagship validation succeeded! Full trace captured in $LOGFILE" | tee -a $LOGFILE
