import * as child_process from 'child_process';
import * as fs from 'fs';
import * as path from 'path';
import { ethers } from 'ethers';
import * as dotenv from 'dotenv';

// Load variables from root .env
dotenv.config({ path: path.resolve(__dirname, '../.env') });

const VAULT_ADDRESS = "0x42f60abfeb12ef53db0c05983d5da76386de2ff8";
const VAULT_ABI = [
    "function executeIntent(bytes calldata proof, bytes calldata publicValues) external",
    "event IntentExecuted(string message, bool success)"
];

export function validateJournal(output: string, expectedMessage: string): boolean {
    const lines = output.split('\n');
    const journalMatch = lines.find(line => line.includes('Successfully verified and committed message:'));

    if (!journalMatch) {
        throw new Error('Verification failed: Journal commit missing from node output');
    }

    if (!journalMatch.includes(expectedMessage)) {
        throw new Error(`DON Consensus Failed: Journal Mismatch Detected`);
    }

    return true;
}

async function runOracle() {
    const parentIntentPath = path.resolve(__dirname, '../1-client/intent.json');
    if (!fs.existsSync(parentIntentPath)) {
        console.error("intent.json not found! Run the 1-client phase first.");
        process.exit(1);
    }

    const intentData = JSON.parse(fs.readFileSync(parentIntentPath, 'utf8'));
    const expectedMessage = intentData.message;

    console.log(`[DON ORCHESTRATOR] Initializing verification sequence for intent: ${expectedMessage}`);

    try {
        console.log(`[DON ORCHESTRATOR] Executing SP1 STARK Proof generation via zkvm-coprocessor...`);
        // Trigger the ZK-Coprocessor process block
        const isDebug = process.env.DEBUG_DON === 'true';
        if (isDebug) console.log(`[DON DEBUG] Triggering Proof generation with RUST_LOG=script=debug,sp1_sdk=info`);
        
        const dockerVerbosity = isDebug ? '-e RUST_LOG=script=debug,sp1_sdk=info' : '';
        const output = child_process.execSync(`docker run -v ${path.resolve(__dirname, '..')}:/app/output ${dockerVerbosity} zkvm-coprocessor`, { encoding: 'utf8' });
        
        console.log("------------------- DOCKER STARK OUTPUT -------------------");
        console.log(output);
        console.log("-----------------------------------------------------------");

        if (validateJournal(output, expectedMessage)) {
            console.log(`[DON CONSENSUS ACHIEVED] ZK-STARK Proof Verified for payload: ${expectedMessage}`);
            
            console.log(`[DON L2 ROUTING] Preparing transaction for EVM Settlement layer...`);

            // Read the generated STARK components from disk
            const proofPath = path.resolve(__dirname, '../proof.json');
            if(!fs.existsSync(proofPath)) {
                throw new Error("Critical: proof.json was not generated by the SP1 host layer!");
            }

            const proofData = JSON.parse(fs.readFileSync(proofPath, 'utf8'));
            
            const provider = new ethers.JsonRpcProvider(process.env.BASE_SEPOLIA_RPC_URL);
            const wallet = new ethers.Wallet(process.env.PRIVATE_KEY as string, provider);
            const vault = new ethers.Contract(VAULT_ADDRESS, VAULT_ABI, wallet);

            console.log(`[DON L2 ROUTING] Submitting proof envelope to Base Sepolia QuantumVault at: ${VAULT_ADDRESS}`);
            
            try {
                // Execute STARK validation against the L2 Network
                const tx = await vault.executeIntent(proofData.proofBytes, proofData.publicValues);
                console.log(`[DON TX BROADCASTED] Hash: ${tx.hash}`);
                console.log(`[DON L2 SETTLEMENT] Waiting for network block confirmation...`);
                
                const receipt = await tx.wait();
                console.log(`[DON PIPELINE SUCCESS] Intent Executed on Chain! Block: ${receipt.blockNumber}`);
            } catch (rpcError: any) {
                // Handle expected revert mechanics for demo display (e.g. proof replays, network failures)
                console.error(`[DON EVM REVERT] The settlement layer reverted the transaction.`);
                console.error(`Reason: ${rpcError.reason || rpcError.message}`);
            }

        }
    } catch (e) {
        console.error(`[DON CRITICAL FAILURE] Execution trace interrupted: ${e}`);
        process.exit(1);
    }
}

// Ensure execution triggers
if (require.main === module) {
    runOracle();
}
