base-sepolia:
  user-workflow:
    workflow-name: "post-quantum-zk-orchestrator"
  workflow-artifacts:
    workflow-path: "./oracle.ts"
    config-path: "./config.json"
    secrets-path: "./secrets.yaml"
  rpcs:
    - chain-name: "ethereum-testnet-sepolia-base-1"
      url: "https://sepolia.base.org"
